version: '3.4'

services:
  webui:
    image: ${DOCKER_REGISTRY-}webui
    build:
      context: .
      dockerfile: src\WebUI\Dockerfile
    depends_on:
        - db
  db:
    image: "mcr.microsoft.com/mssql/server"
    volumes: 
        - ./src/Infrastructure/3rdPartyApi/Ing/Scripts/certs:/certs
        - ./src/Infrastructure/3rdPartyApi/Ing/Scripts:/Scripts
    environment:
        SA_PASSWORD: "Your_password123"
        ACCEPT_EULA: "Y"
        UseMoreThan2MeaslyGBofRAM: "Y"
    mem_limit: 2G
    ports:
        - 1433:1433 